# Generated by Django 3.1.4 on 2021-05-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45, null=True)),
                ('first_name', models.CharField(max_length=45, null=True)),
                ('phone_number', models.CharField(max_length=45, null=True)),
                ('image_url', models.URLField(max_length=2000)),
                ('coupon', models.ManyToManyField(through='products.UserCoupon', to='products.Coupon')),
                ('dinning', models.ManyToManyField(through='products.Review', to='products.Dinning')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
