# Generated by Django 3.1.4 on 2021-05-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_coupon_review_usercoupon'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coupon',
            field=models.ManyToManyField(through='products.UserCoupon', to='products.Coupon'),
        ),
        migrations.AddField(
            model_name='user',
            name='dinning',
            field=models.ManyToManyField(through='products.Review', to='products.Dinning'),
        ),
    ]
