# Generated by Django 3.2 on 2021-05-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_dinning',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_room',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='latitude',
            field=models.DecimalField(decimal_places=17, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='longitude',
            field=models.DecimalField(decimal_places=17, max_digits=20, null=True),
        ),
    ]
