# Generated by Django 3.1.4 on 2021-05-04 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210504_0430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinning',
            name='description',
        ),
    ]
