# Generated by Django 3.1.4 on 2021-05-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_dinning_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_dinning',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_room',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
