# Generated by Django 3.1.4 on 2021-05-06 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_is_popular'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
            options={
                'db_table': 'activities',
            },
        ),
        migrations.RemoveField(
            model_name='dinningoption',
            name='description',
        ),
        migrations.RemoveField(
            model_name='dinningoption',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_popular',
        ),
        migrations.AddField(
            model_name='product',
            name='is_activity',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ActivityImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=2000)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.activity')),
            ],
            options={
                'db_table': 'activity_images',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.activity'),
        ),
    ]
