# Generated by Django 3.1.4 on 2021-05-06 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210506_0643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='activity',
        ),
        migrations.AddField(
            model_name='product',
            name='actjivity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.activity'),
        ),
    ]
