# Generated by Django 3.1.4 on 2021-05-06 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210506_0643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='actjivity',
            new_name='activity',
        ),
    ]
