# Generated by Django 3.1.4 on 2021-05-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210506_0644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityimage',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='activity',
        ),
        migrations.AddField(
            model_name='product',
            name='is_popular',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='ActivityImage',
        ),
    ]
