# Generated by Django 3.1.4 on 2021-05-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210506_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
