# Generated by Django 3.1.4 on 2021-05-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_coupon_review_usercoupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinningtype',
            name='name',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='name',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
