# Generated by Django 3.2 on 2021-05-04 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('code', models.CharField(max_length=45)),
                ('discount_rate', models.DecimalField(decimal_places=0, max_digits=2)),
                ('expire_date', models.DateField()),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
            options={
                'db_table': 'coupons',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45, null=True)),
                ('first_name', models.CharField(max_length=45, null=True)),
                ('phone_number', models.CharField(max_length=45, null=True)),
                ('image_url', models.URLField(max_length=2000)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'user_coupons',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='coupon',
            field=models.ManyToManyField(through='users.UserCoupon', to='users.Coupon'),
        ),
        migrations.AddField(
            model_name='user',
            name='dinning',
            field=models.ManyToManyField(through='products.Review', to='products.Dinning'),
        ),
    ]
